Add event tracking
alphagov/paas-product-pages pull request #120
Opened 2021-04-27 08:05 UTC by kr8n3r

2021-04-28 11:02 UTC, 0atman requested changes
Just a few questions about this, maybe I've been out of the js game too long, please accept my apologies if I've got the wrong idea.

I find it very strange that analytics.js has inconsistent semicolon use. Personally, I don't use them in my js projects (I use https://standardjs.com to warn me in the very few cases where they're needed, but maybe we use something else in paas?) is this an oversight or to a standard?

Thanks!

2021-04-28 11:07 UTC, 0atman commented on javascripts/analytics.js
> +      externalLinkRegex = /^(?=.*(http(s)|mailto))(?:(?!cloud\.service).)*$/g,
screenshot from https://regexr.com/

2021-04-28 11:25 UTC, kr8n3r commented on javascripts/analytics.js
> +  function gtag(){
was going by https://developers.google.com/analytics/devguides/collection/gtagjs but certainly can update that

2021-04-28 11:27 UTC, kr8n3r commented on javascripts/analytics.js
> +      externalLinkRegex = /^(?=.*(http(s)|mailto))(?:(?!cloud\.service).)*$/g,
re: standardJS we currently don't have it setup in this project, paas-admin uses `eslint`

I'll remove all semicolons in here to make it compatible down the line

2021-04-28 11:38 UTC, kr8n3r commented on javascripts/analytics.js
> +      externalLinkRegex = /^(?=.*(http(s)|mailto))(?:(?!cloud\.service).)*$/g,
updated

2021-04-28 13:51 UTC, 0atman commented on javascripts/analytics.js
> +      externalLinkRegex = /^(?=.*(http|mailto))(?:(?!cloud\.service\.gov\.uk).)*$/g,
Now we're talking! Looks good to me :ok_hand: 

![Screenshot from 2021-04-28 14-50-07](https://user-images.githubusercontent.com/114097/116415282-2dc9dd00-a831-11eb-9d57-9fbcee6da3aa.png)

2021-04-28 13:54 UTC, kr8n3r commented
@0atman  added a commit just now :)

2021-04-28 14:37 UTC, kr8n3r commented
need to drop the standard fix commit

2021-04-29 09:04 UTC, 0atman approved these changes

2021-04-30 14:20 UTC, merged