Update hero copy and link
alphagov/paas-product-pages pull request #124
Opened 2021-05-06 13:33 UTC by markpeterbuckley

Changes strapline, added additional link to find out more

2021-05-06 13:57 UTC, 0atman requested changes

2021-05-06 13:57 UTC, 0atman commented on components/MastHead/index.tsx
> +              If you work in the public sector, use GOV.UK Platform as a Service to host your services without worrying about infrastructure.
as line 11, lets call these "applications" right?

2021-05-06 14:03 UTC, kr8n3r reviewed
@SaraC19 do we update the event labels as well?

2021-05-12 08:39 UTC, SaraC19 commented
@kr8n3r  - when this goes live, yes please to update the event label to the new words

2021-05-12 14:30 UTC, LeePorte commented on components/MastHead/index.tsx
> +              If you work in the public sector, use GOV.UK Platform as a Service to host your services without worrying about infrastructure.
Agree

2021-07-16 07:01 UTC, kr8n3r commented
superceded by https://github.com/alphagov/paas-product-pages/pull/130 and these suggestions included

2021-07-16 07:01 UTC, closed without merging